[workspace]
resolver = "3"
members = ["device"]
cargo-features = ["per-package-target"]

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

